WebProyecto/Areas/Admin/Controllers/BodegaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebProyecto.AccesoDatos.Repositorio.IRepositorio;
using WebProyecto.Modelos;
using WebProyecto.Utilities;

namespace WebProyecto.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = DS.Role_Admin)]

    public class BodegaController : Controller
    {
        private readonly IUnidadTrabajo _unidadTrabajo;
        public BodegaController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo = unidadTrabajo;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Upsert(int? id)
        {
            Bodega bodega = new Bodega();
            if (id == null)
            {
                //Esto es para crear una nueva bodega (insert)
                return View(bodega);
            }
            //actualizamos un registro Bodega existente
            bodega = _unidadTrabajo.Bodega.Obtener(id.GetValueOrDefault());
            if (bodega == null)
            {
                return NotFound();
            }
            return View(bodega);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Bodega bodega)
        {
            if (ModelState.IsValid)
            {
                if (bodega.id == 0) //nuevo registro
                {
                    _unidadTrabajo.Bodega.Agregar(bodega);
                    
                }
                else
                {
                    _unidadTrabajo.Bodega.Actualizar(bodega);
                }
                _unidadTrabajo.Guardar();
                return RedirectToAction(nameof(Index));
            }
            return View(bodega);
        }
        #region API
        [HttpGet]
        public IActionResult ObtenerTodos()
        {
            var todos = _unidadTrabajo.Bodega.ObtenerTodos();
            return Json(new { data = todos });
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var bodegaDb = _unidadTrabajo.Bodega.Obtener(id);
            if (bodegaDb == null)
            {
                return Json(new { success = false, message = "Error al borrar la bodega " });
            }
            else
                _unidadTrabajo.Bodega.Remover(bodegaDb);
            _unidadTrabajo.Guardar();
            return Json(new { success = true, message = "Bodega borrada exitosamente" });
        }
        #endregion
    }
}

WebProyecto/Areas/Admin/Controllers/FlorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Rotativa;
using Rotativa.AspNetCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebProyecto.AccesoDatos.Repositorio.IRepositorio;
using WebProyecto.Modelos;
using WebProyecto.Modelos.ViewModels;
using WebProyecto.Utilities;

namespace WebProyecto.Areas.Admin.Controllers
{

    [Area("Admin")]


    [Authorize(Roles = DS.Role_Admin + "," + DS.Role_Inventario)]


    public class FlorController : Controller
    {

        private readonly IUnidadTrabajo _unidadTrabajo;
        private readonly IWebHostEnvironment _hostEnvironment;
        public FlorController(IUnidadTrabajo unidadTrabajo,
        IWebHostEnvironment hostEnvironment)
        {
            _unidadTrabajo = unidadTrabajo;
            _hostEnvironment = hostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Upsert(int? id)
        {
            FlorVM florVM = new FlorVM()
            {
                Flor = new Flor(),
                CategoriaFlorLista =
            _unidadTrabajo.CategoriaFlor.ObtenerTodos().Select(c => new SelectListItem
            {
                Text = c.Nombre,
            Value = c.id.ToString()
 }),

 
 PadreLista =
 _unidadTrabajo.Flor.ObtenerTodos().Select(p => new SelectListItem
 {
     Text = p.Descripcion,
     Value = p.Id.ToString()
 })
 };
 if (id == null)
 {
 // Esto es para Crear nuevo Registro
 return View(florVM);
    }
            // Esto es para Actualizar
     florVM.Flor = _unidadTrabajo.Flor.Obtener(id.GetValueOrDefault());
 if (florVM.Flor == null)
 {
 return NotFound();
}
return View(florVM);



 }
 [HttpPost]


[ValidateAntiForgeryToken]
public IActionResult Upsert(FlorVM florVM)
{
    if (ModelState.IsValid)
    {
        // Cargar Imagenes
        string webRootPath = _hostEnvironment.WebRootPath;
        var files = HttpContext.Request.Form.Files;
        if (files.Count > 0)
        {
            /*
            * El método Guid (Identificador único global) puede crear nuevos objetos 
           * como identificadores, mediante la propiedad NewGuid 
            * GUID (o UUID) es un acrónimo de 'Identificador global único' (o 
           'Identificador universal único'). 
            * Es un número entero de 128 bits que se utiliza para identificar recursos.
            */
            string filename = Guid.NewGuid().ToString();
            var uploads = Path.Combine(webRootPath, @"img\flores");
            var extension = Path.GetExtension(files[0].FileName);
             Flor florDB =
             _unidadTrabajo.Flor.Obtener(florVM.Flor.Id);
            if (florDB != null)
               florVM.Flor.ImageUrl = florDB.ImageUrl;
            if (florVM.Flor.ImageUrl != null)
            {
                //Esto es para editar, necesitamos borrar la imagen anterior
                var imagenPath = Path.Combine(webRootPath,
                 florVM.Flor.ImageUrl.TrimStart('\\'));
                if (System.IO.File.Exists(imagenPath))
                {
                    System.IO.File.Delete(imagenPath);
                }
            }
            using (var filesStreams = new FileStream(Path.Combine(uploads,
            filename + extension), FileMode.Create))
            {
                files[0].CopyTo(filesStreams);
            }
               florVM.Flor.ImageUrl = @"\img\flores\"
             + filename + extension;
        }
        else
        {
            // Si en el Update el usuario no cambia la imagen
            if (florVM.Flor.Id != 0)
            {
                        Flor florDB =
                _unidadTrabajo.Flor.Obtener(florVM.Flor.Id);
                florVM.Flor.ImageUrl = florDB.ImageUrl;
            }
        }
        if (florVM.Flor.Id == 0)
        {
            _unidadTrabajo.Flor.Agregar(florVM.Flor);
        }
        else
        {
            _unidadTrabajo.Flor.Actualizar(florVM.Flor);
        }
        _unidadTrabajo.Guardar();
        return RedirectToAction(nameof(Index));
    }
    else
    {
                florVM.CategoriaFlorLista =
        _unidadTrabajo.CategoriaFlor.ObtenerTodos().Select(c => new SelectListItem
        {
            Text = c.Nombre,
            Value = c.id.ToString()
        });

                florVM.PadreLista = _unidadTrabajo.Flor.ObtenerTodos().Select(p =>
        new SelectListItem
        {
            Text = p.Descripcion,
            Value = p.Id.ToString()
        });
        if (florVM.Flor.Id != 0)
        {
                    florVM.Flor =
            _unidadTrabajo.Flor.Obtener(florVM.Flor.Id);
        }
    }
    return View(florVM.Flor);

}

        public IActionResult ImprimirFlores()
        {
            FlorVM florVM = new FlorVM();
            florVM.FlorLista =
            _unidadTrabajo.Flor.ObtenerTodos(IncluirPropiedades: "CategoriaFlor");
            return new ViewAsPdf("ImprimirFlores", florVM)
            {
                FileName = "ListaFlores" + ".pdf",
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape,
                PageSize = Rotativa.AspNetCore.Options.Size.A4,
                CustomSwitches = "--page-offset 9 --footer-center [page] --footer-font-size 12"
            };
        }


        #region API
        [HttpGet]
public IActionResult ObtenerTodos()
{
    var todos =
    _unidadTrabajo.Flor.ObtenerTodos(IncluirPropiedades: "CategoriaFlor");
    return Json(new { data = todos });
}
[HttpDelete]
public IActionResult Delete(int id)
{
    var florDb = _unidadTrabajo.Flor.Obtener(id);
    if (florDb == null)
    {
        return Json(new { success = false, message = "Error al Borrar" });
    }
    // Eliminar la Imagen relacionada al producto
    string webRootPath = _hostEnvironment.WebRootPath;
    var imagenPath = Path.Combine(webRootPath, florDb.ImageUrl.TrimStart('\\'));
    if (System.IO.File.Exists(imagenPath))
    {
        System.IO.File.Delete(imagenPath);
    }
    _unidadTrabajo.Flor.Remover(florDb);
    _unidadTrabajo.Guardar();
    return Json(new { success = true, message = "Flor Borrada Exitosamente" });
}
 #endregion
 }













}

WebProyecto/Areas/Admin/Controllers/MarcaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebProyecto.AccesoDatos.Repositorio.IRepositorio;
using WebProyecto.Modelos;
using WebProyecto.Utilities;

namespace WebProyecto.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = DS.Role_Admin)]

    public class MarcaController : Controller
    {
        private readonly IUnidadTrabajo _unidadTrabajo;
        public MarcaController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo = unidadTrabajo;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Upsert(int? id)
        {
            Marca marca = new Marca();
            if (id == null)
            {
                //Esto es para crear una nueva marca (insert)
                return View(marca);
            }
            //actualizamos un registro marca existente
            marca = _unidadTrabajo.Marca.Obtener(id.GetValueOrDefault());
            if (marca == null)
            {
                return NotFound();
                
            }
            return View(marca);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Marca marca)
        {
            if (ModelState.IsValid)
            {
                if (marca.id == 0) //nuevo registro
                {
                    _unidadTrabajo.Marca.Agregar(marca);
                }
                else
                {
                    _unidadTrabajo.Marca.Actualizar(marca);
                }
                _unidadTrabajo.Guardar();
                return RedirectToAction(nameof(Index));
            }
            return View(marca);
        }
        #region API
        [HttpGet]
        public IActionResult ObtenerTodos()
        {
            var todos = _unidadTrabajo.Marca.ObtenerTodos();
            return Json(new { data = todos });
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var marcaDb = _unidadTrabajo.Marca.Obtener(id);
            if (marcaDb == null)
            {
                return Json(new { success = false, message = "Error al borrar la marca " });
            }
            else
                _unidadTrabajo.Marca.Remover(marcaDb);
            _unidadTrabajo.Guardar();
            return Json(new { success = true, message = "Marca borrada exitosamente" });
        }
        #endregion
    }

}

WebProyecto/Areas/Admin/Controllers/UsuarioController.cs
using WebProyecto.Data;
using WebProyecto.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebProyecto.Areas.Inventario.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = DS.Role_Admin)]
    public class UsuarioController : Controller
    {
        private readonly ApplicationDbContext _db;

        public UsuarioController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }


        #region API

        [HttpGet]
        public IActionResult ObtenerTodos()
        {
            var usuarioLista = _db.UsuarioAplicacion.ToList();
            var userRole = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();

            foreach (var usuario in usuarioLista)
            {
                var roleId = userRole.FirstOrDefault(u => u.UserId == usuario.Id).RoleId;
                usuario.Role = roles.FirstOrDefault(u => u.Id == roleId).Name;
            }
            return Json(new { data = usuarioLista });
        }


        [HttpPost]
        public IActionResult BloquearDesbloquear([FromBody] string id)
        {
            var usuario = _db.UsuarioAplicacion.FirstOrDefault(u => u.Id == id);
            if (usuario == null)
            {
                return Json(new { success = false, message = "Error de Usuario" });
            }

            if (usuario.LockoutEnd != null && usuario.LockoutEnd > DateTime.Now)
            {
                // Usuario Bloqueado
                usuario.LockoutEnd = DateTime.Now;
            }
            else
            {
                usuario.LockoutEnd = DateTime.Now.AddYears(1000);
            }
            _db.SaveChanges();
            return Json(new { success = true, message = "Operacion Exitosa" });

        }

        #endregion
    }

}

WebProyecto/Views/Shared/_BotonesActualizarRegresar.cshtml
@model int
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary text-light rounded-pill form-control"
                asp-route-id="@Model">
            <i class="fa fa-pencil-square-o fa-lg"></i>
            Actualizar
        </button>
    </div>
    <div class="col">
        <a asp-action="Index"
           class="btn btn-success rounded-pill form-control">
            <i class="fa fa-external-link"> Regresar</i>
        </a>
    </div>
</div>

WebProyecto/Views/Shared/_BotonesCrearRegresar.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary rounded-pill form-control">
            <i class="fa fa-plus-circle fa-lg"></i>
            Crear
        </button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success rounded-pill form-control">
            <i class="fa fa-external-link fa-lg"></i>
            Regresar
        </a>
    </div>
</div>

WebProyecto/Views/Shared/_Layout.cshtml
@using WebProyecto.Utilities;
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccesor;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]WebProyecto</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <style>
        .navbar, .container {
            font-size: 20px;
            font-family: Roboto;
        }
    </style>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-5 fixed-top">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>


                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        @if (User.IsInRole(DS.Role_Admin) || User.IsInRole(DS.Role_Inventario))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Mantenimiento
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    @if (User.IsInRole(DS.Role_Admin))
                                    {
                                        <a class="dropdown-item"
                                           asp-area="Admin"
                                           asp-controller="Bodega"
                                           asp-action="Index">
                                            <i class="fas fa-home"></i>
                                            Bodegas
                                        </a>

                                        <div class="dropdown-divider bg-light"></div>

                                        <a class="dropdown-item"
                                           asp-area="Admin"
                                           asp-controller="CategoriaPerfume"
                                           asp-action="Index">
                                            <i class="fas fa-cogs"></i>
                                            Categorías de Perfume
                                        </a>

                                        <div class="dropdown-divider bg-light"></div>

                                        <a class="dropdown-item"
                                           asp-area="Admin"
                                           asp-controller="CategoriaFlor"
                                           asp-action="Index">
                                            <i class="fas fa-cogs"></i>
                                            Categorías de Flor
                                        </a>

                                        <div class="dropdown-divider bg-light"></div>

                                        <a class="dropdown-item"
                                           asp-area="Admin"
                                           asp-controller="Marca"
                                           asp-action="Index">
                                            <i class="fas fa-award"></i>
                                            Marcas
                                        </a>

                                        <div class="dropdown-divider bg-light"></div>
                                    }
                                    @if (User.IsInRole(DS.Role_Admin) || User.IsInRole(DS.Role_Inventario))
                                    {
                                        <a class="dropdown-item"
                                           asp-area="Admin"
                                           asp-controller="Perfume"
                                           asp-action="Index">
                                            <i class="fas fa-cog"></i>
                                            Perfumes
                                        </a>

                                        <div class="dropdown-divider bg-light"></div>

                                        <a class="dropdown-item"
                                           asp-area="Admin"
                                           asp-controller="Flor"
                                           asp-action="Index">
                                            <i class="fas fa-cog"></i>
                                            Flores
                                        </a>

                                        <div class="dropdown-divider bg-light"></div>
                                    }
                                    @if (User.IsInRole(DS.Role_Admin))
                                    {
                                        <a class="dropdown-item"
                                           asp-area="Admin"
                                           asp-controller="Usuario"
                                           asp-action="Index">
                                            <i class="fas fa-user-lock"></i>
                                            Usuarios
                                        </a>
                                    }

                                </div>
                            </li>
                        }
                        @if (User.IsInRole(DS.Role_Admin) || User.IsInRole(DS.Role_Inventario))
                        {
                            <li class="nav-item">
                                <a class="nav-link"
                                   asp-area="Inventario"
                                   asp-controller="Inventario"
                                   asp-action="Index">
                                    Inventario
                                </a>
                            </li>
                        }


                        @if (User.IsInRole(DS.Role_Admin)
                       || User.IsInRole(DS.Role_Inventario)
                       || User.IsInRole(DS.Role_Ventas))
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="#">Consultas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Reportes</a>
                            </li>
                        }


                        @*@if (HttpContextAccesor.HttpContext.Session.GetInt32(DS.ssCarroCompras) != null)
                        {
                            <li>
                                <a asp-area="Inventario" asp-controller="CarroCompras" asp-action="Index" class="nav-link">

                                    @{
                                        var cantidadProducto = HttpContextAccesor.HttpContext.Session.GetInt32(DS.ssCarroCompras);
                                    }
                                    <i class="fas fa-shopping-cart"></i>
                                    &nbsp;(@cantidadProducto)
                                </a>
                            </li>
                        }*@



                        @*else
                            {
                                <li>
                                    <a href="#" class="nav-link">
                                        <i class="fas fa-shopping-cart"></i>
                                        &nbsp;(0)
                                    </a>
                                </li>
                            }*@
                    </ul>
                    <partial name="_LoginPartial" />
                </div>

            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary text-white-50 fixed-bottom">
        <div class="container">
            &copy; 2022 - Distribuidora Acme, Nicoya, Guanacaste
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>